let DobbleSymbols = {}

DobbleSymbols.SYMBOLS = [
  { id: '00', category: 'green', name: 'Peinture' },
  { id: '01', category: 'green', name: 'Dinosaure' },
  { id: '02', category: 'green', name: 'Art', name2: 'Tortue' },
  { id: '03', category: 'green', name: 'Carotte' },
  { id: '04', category: 'green', name: 'Arbre' },
  { id: '05', category: 'green', name: 'Cactus' },
  { id: '06', category: 'green', name: 'Trefle' },
  { id: '07', category: 'green', name: 'Pomme' },
  { id: '08', category: 'green', name: "Point d'interrogation" },
  { id: '09', category: 'purple', name: 'Chat' },
  { id: '10', category: 'purple', name: 'Dragon' },
  { id: '11', category: 'purple', name: 'Ciseaux' },
  { id: '12', category: 'purple', name: 'Ok', name2: 'Oiseau' },
  { id: '13', category: 'purple', name: "Toile d'arraignée" },
  { id: '14', category: 'purple', name: 'Oeil' },
  { id: '15', category: 'purple', name: 'Dobble' },
  { id: '16', category: 'purple', name: 'Bougie' },
  { id: '17', category: 'orange', name: 'Voiture' },
  { id: '18', category: 'orange', name: 'Stop', name2: 'Marteau' },
  { id: '19', category: 'orange', name: 'Clé de sol' },
  { id: '20', category: 'orange', name: 'Biberon' },
  { id: '21', category: 'orange', name: 'Ancre' },
  { id: '22', category: 'orange', name: 'Bonhomme' },
  { id: '23', category: 'orange', name: 'Horloge' },
  { id: '24', category: 'orange', name: 'Clé' },
  { id: '25', category: 'bleu', name: 'Glacon' },
  { id: '26', category: 'bleu', name: 'Dauphin' },
  { id: '27', category: 'bleu', name: 'Fantôme' },
  { id: '28', category: 'bleu', name: 'Bonhomme de neige' },
  { id: '29', category: 'bleu', name: 'Crayon' },
  { id: '30', category: 'bleu', name: 'Igloo' },
  { id: '31', category: 'bleu', name: "Goutte d'eau" },
  { id: '32', category: 'bleu', name: 'Flocon' },
  { id: '33', category: 'rouge', name: 'Cible' },
  { id: '34', category: 'rouge', name: 'Clown' },
  { id: '35', category: 'rouge', name: 'Coeur' },
  { id: '36', category: 'rouge', name: "Feuille d'érable" },
  { id: '37', category: 'rouge', name: 'Lèvres' },
  { id: '38', category: 'rouge', name: 'Feu' },
  { id: '39', category: 'rouge', name: 'Coccinelle' },
  { id: '40', category: 'rouge', name: 'Sens interdit' },
  { id: '41', category: 'yellow', name: 'Chien' },
  { id: '42', category: 'yellow', name: 'Soleil' },
  { id: '43', category: 'yellow', name: 'Eclair' },
  { id: '44', category: 'yellow', name: 'Ampoule' },
  { id: '45', category: 'yellow', name: 'Lune' },
  { id: '46', category: 'yellow', name: "Point d'exclamation" },
  { id: '47', category: 'yellow', name: 'Fromage' },
  { id: '48', category: 'yellow', name: 'Fleur' },
  { id: '49', category: 'black', name: 'Zèbre' },
  { id: '50', category: 'black', name: 'Verrou' },
  { id: '51', category: 'black', name: 'YingYang' },
  { id: '52', category: 'black', name: 'Arraignée' },
  { id: '53', category: 'black', name: 'Tête de mort' },
  { id: '54', category: 'black', name: 'Cavalier' },
  { id: '55', category: 'black', name: 'Lunettes' },
  { id: '56', category: 'black', name: 'Bombe' }
]

export default DobbleSymbols
